---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - curl
    - ca-certificates

- name: Create directory for Docker's GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Add Docker repo
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update

- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker and related packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Show Docker version
  shell: docker -v
  register: docker_version

- name: Docker version
  debug:
    var: docker_version

- name: Show docker-compose version
  shell: docker compose -v
  register: docker_compose_version

- name: Docker compose version
  debug:
    var: docker_compose_version
